// <auto-generated />
using System;
using Infrastructure.Persistence.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521031758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.FriendEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("friends", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.FriendRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlackPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("IncrementPerMoveSec")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialTimeSec")
                        .HasColumnType("integer");

                    b.Property<string>("Moves")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTimeUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("TerminationReason")
                        .HasColumnType("integer");

                    b.Property<Guid>("WhitePlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.GameInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("game_invitations", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.SkinEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("BlackBoardImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("EndFightLoseImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EndFightWinImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Figure")
                        .HasColumnType("integer");

                    b.Property<byte[]>("IdleImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("StartFightLoseImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("StartFightWinImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("WhiteBoardImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("skins", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.SkinSetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("skin_sets", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("LootBoxCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserFigureSkinEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Figure")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkinId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Figure");

                    b.HasIndex("SkinId");

                    b.ToTable("user_figure_skins", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserSkinEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkinId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SkinId");

                    b.HasIndex("SkinId");

                    b.ToTable("user_skins", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.FriendEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "Friend")
                        .WithMany("FriendOf")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.FriendRequestEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.GameEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "BlackPlayer")
                        .WithMany("BlackGames")
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "WhitePlayer")
                        .WithMany("WhiteGames")
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlackPlayer");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.GameInvitationEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "Receiver")
                        .WithMany("ReceivedGameInvitations")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "Sender")
                        .WithMany("SentGameInvitations")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.SkinEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.SkinSetEntity", "Set")
                        .WithMany("Skins")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserFigureSkinEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.SkinEntity", "Skin")
                        .WithMany()
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "User")
                        .WithMany("EquippedSkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserSkinEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.SkinEntity", "Skin")
                        .WithMany("Owners")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.EfCore.Entities.UserEntity", "User")
                        .WithMany("OwnedSkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.SkinEntity", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.SkinSetEntity", b =>
                {
                    b.Navigation("Skins");
                });

            modelBuilder.Entity("Infrastructure.Persistence.EfCore.Entities.UserEntity", b =>
                {
                    b.Navigation("BlackGames");

                    b.Navigation("EquippedSkins");

                    b.Navigation("FriendOf");

                    b.Navigation("Friends");

                    b.Navigation("OwnedSkins");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("ReceivedGameInvitations");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SentGameInvitations");

                    b.Navigation("WhiteGames");
                });
#pragma warning restore 612, 618
        }
    }
}
